version: '3.8'

services:
  db:
    image: postgres:15
    container_name: turo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: turo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: turo_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env.example # In real prod, use a real .env
    environment:
      POSTGRES_SERVER: db
      SQLALCHEMY_DATABASE_URI: postgresql+asyncpg://postgres:password@db/turo_db

volumes:
  postgres_data:
